### PR TITLE
Changed exception to error message

### PR DESCRIPTION
**Pull request by glasswalk3r**
Instead of raising a timeout exception when trying to reach AWS EC2 metadata, now the attempted will only generate an error message into `STDERR`.

### CODE REVIEW

**Comment by glasswalk3r** [comment]
Not sure although if there is a better way to check on this... maybe some default environment variable in EC2 instances that could be used to check if awsecret is actually running on EC2 or not?

**Comment by k1LoW** [comment]
Thank you !!! @glasswalk3r !!!! GREAT !!!

Could you merge master branch ? ( Looks CI still fail

**Comment by glasswalk3r** [comment]
Done!

**Comment by k1LoW** [comment]
> maybe some default environment variable in EC2 instances that could be used to check if awsecret is actually running on EC2 or not?

No, there is not.

**Comment by glasswalk3r** [comment]
Well, I guess that all we can do for now.
Or maybe create an specific exception to be `rescue`d?
Anyway, I guess this is ready to be merged. :-D

**Comment by k1LoW** [comment]
Oh! Thank you !!

**Comment by k1LoW** [comment]
Released as v1.15.0.

**Pull request merged**
