### PR TITLE
Adding in assumed role external_id option

### PR DESCRIPTION
**Pull request by craigmonson**
Added:
  * external_id option for assumed roles
  * some more tests
  * some reformatting in assignment blocks (completely visual)
  * use of require_relative in some cases so you can run test commands locally.

### CODE REVIEW

**Comment by craigmonson** [comment]
The failing check is rubocop.  All unit tests are passing. *shrug*

**Comment by k1LoW** [comment]
Oh @craigmonson ! Great work ! Thank you !

**Comment by craigmonson** [comment]
@k1LoW Np!  Think we can get this merged in and pushed out to rubygems?  I'll open up an issue with awspec to bump the awsecrets version.

**Comment by k1LoW** [comment]
Released as v1.14.0.

**Pull request merged**
